spring.application.name=literalura

# ==========================================
# CONFIGURAÇÃO DO BANCO DE DADOS (DataSource)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5435/screenfrases
spring.datasource.username=admin
spring.datasource.password=admin

# ==========================================
# CONFIGURAÇÃO DO JPA / HIBERNATE
# ==========================================

# 'validate': valida se o schema do banco corresponde às entidades.
# 'update': atualiza o schema (bom para desenvolvimento).
# 'create': recria o banco a cada execução (bom para testes).
# 'create-drop': cria e destrói o banco a cada execução.
# 'none': não faz nada (ideal para produção com migrations).
spring.jpa.hibernate.ddl-auto=update

# Ativar a exibição de SQL no console é muito útil para depuração.
spring.jpa.show-sql=true

# Formata o SQL exibido no console para melhor legibilidade.
spring.jpa.properties.hibernate.format_sql=true